name: test-ci

on:
  push:
    branches:
      - 'dev'
      - 'master-staging'
      - 'master'

jobs:
  test-back:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out code
        uses: actions/checkout@v2
      -
        name: run tests for 2104-wns-paris-agowork-back
        run: npm install && npm run test